apiVersion: v1
kind: Service
metadata:
  namespace: copilot-cli-ns
  name: copilot-cli-svc-nodeport
spec:
  type: NodePort
  ports:
    - port: 8321
      targetPort: 8321
      nodePort: 32424
      protocol: TCP
  selector:
    env: copilot-cli-pod
